### ISSUE TITLE
Traces missing with rapid duplicate calls to dotnet core Web API endpoint

### ISSUE THREAD

**Issue by andy-g** [opentracing-contrib/csharp-netcore#22]
I'm new to OpenTracing & Jaeger, so I may simply be getting something wrong with the setup, but traces are logged fine, except when I make a rapid set of calls to my app. In the case where I make 10 successive calls, only 1 or 2 of the calls will be visible in Jaeger afterwards.

It feels like a sampling issue, but as you can see, I've specified `new ConstSampler(true)` which I'd expect should send every span to Jaeger.

I'm using the following command to make sure my requests are consistent, in the below examples I cancelled the curl command after 5 iterations.

```sh
while true; do curl -s http://localhost:5000/api/Todo | grep --color -E 'id'; sleep .5; done;
```

I'm registering the services in `ConfigureServices` of my `Startup.cs`:

```c#
services.AddOpenTracing();

// Adds the Jaeger Tracer.
services.AddSingleton<ITracer>(serviceProvider =>
{
    string serviceName = serviceProvider.GetRequiredService<IHostingEnvironment>().ApplicationName;

    // This will log to a default localhost installation of Jaeger.
    var tracer = new Tracer.Builder(serviceName)
        .WithSampler(new ConstSampler(true))
        .Build();

    // Allows code that can't use DI to also access the tracer.
    GlobalTracer.Register(tracer);

    return tracer;
});
```

If I manually add logging in my controller method like this:

```c#
using (var scope = _tracer.BuildSpan ("Action ToDoController.GetAll").StartActive (true)) {
    ...
}
```

... these are also lost along with the root span.

If I remove the `services.AddOpenTracing();` from my `Startup.cs` then when I re-run my curl request 5 times, I get all 5 logs.

See a jeager screenshot below, the 1 trace at the bottom shows 4 spans (the extra spans are as a result of `AddOpenTracing` but I'm only getting the 1 trace - I should be getting 5), the other traces are visible for each curl request (once `AddOpenTracing` is removed) but only shows the 1 span I manually added on the controller method.

![image](https://user-images.githubusercontent.com/557065/43459203-105d15cc-94cd-11e8-9afd-be0d3fd56c0c.png)

Any help or insights would be hugely appreciated.

Thanks for your work on this, I love the idea of automatically instrumenting jaeger tracing, and would love to see this grow & develop - and keen to help in any way I can.

**Comment by andy-g** [comment]
No problem, I'll try clean it up a bit and add a simple project / example on GitHub, will post a link here once I've uploaded it.

**Comment by andy-g** [comment]
Hi @cwe1ss, I've pushed a demo project to a GitHub repo:
https://github.com/andy-g/opentracing-demo

I setup the project to run in docker too, and noticed that in docker it seemed to run fine, so I'm not sure if it could be an issue running it on Mac OS - but I haven't had issues with dotnet running on different environments up to now.

It is a consistent and predictable issue when running it locally though.

**Comment by cwe1ss** [comment]
Please test this again with the newest version of this library and your tracer if it's still relevant to you and let us know if there's still issues.
