### ISSUE TITLE
Trace filtering

### ISSUE THREAD

**Issue by jrouaix** [opentracing-contrib/csharp-netcore#28]
I'm not sure this is a question for here or more for JaegerTracing (it have a sampler, but the signature is not able to enable what I want).

To you know a way to remove some traces, according to some rules ? *
my case is :
   I want to remove noise from the GET /health endpoint of my services.

**Comment by cwe1ss** [comment]
You can use the `IgnorePatterns` property on `HttpHandlerDiagnosticOptions` (for outgoing HTTP requests) and `HostingOptions` (for incoming HTTP requests).

I'm already using this in the samples to exclude the outgoing HTTP requests to the Jaeger API - see: https://github.com/opentracing-contrib/csharp-netcore/blob/d165512a9c316bc89590dd65534bce2b76fcfca4/samples/Shared/JaegerServiceCollectionExtensions.cs#L41-L44

You would need similar code configuring the `HostingOptions` class.

Does that help?

**Comment by toftware** [comment]
You need to use [AspNetCoreDiagnosticOptions](https://github.com/opentracing-contrib/csharp-netcore/blob/d165512a9c316bc89590dd65534bce2b76fcfca4/src/OpenTracing.Contrib.NetCore/AspNetCore/AspNetCoreDiagnosticOptions.cs).

```csharp
services.Configure<AspNetCoreDiagnosticOptions>(options =>
{
	options.Hosting.IgnorePatterns.Add(x =>
	{
	      return x.Request.Path == "/health";
	});
});
```

**Comment by jrouaix** [comment]
@cwe1ss  @toftware thank you ! it's working fine !

**Comment by cwe1ss** [comment]
@jrouaix sorry for giving you the wrong info and @toftware thx for providing the proper guidance!

**Comment by toftware** [comment]
I had the same issue and was following this issue and easily spotted the mistake.

Should we write some documentation on how the ignore / other options work, or where to find them? 
Or is that something that will happen when the API's are mature enough.

**Comment by d1mnewz** [comment]
It will be definitely useful to have in the documentation. Would you let me do that improvement? @cwe1ss

**Comment by cwe1ss** [comment]
@d1mnewz sure!! More docs are always welcome! Thank you!

**Comment by cwe1ss** [comment]
Sorry. Didn't mean to reopen this issue. Please just create a PR with your proposed docs.
