### ISSUE TITLE
Consider targeting .NET Standard 2.0

### ISSUE THREAD

**Issue by paulomorgado** [opentracing-contrib/csharp-netcore#30]
ASP.NET Core runs on .NET Core and .NET Framework.

Both .NET Core and .NET Framework (depending on the versions) can use .NET Standard libraries.

Targeting .NET Core only will not allow its use on .NET Framework.

**Comment by cwe1ss** [comment]
Duplicate - see https://github.com/opentracing-contrib/csharp-netcore/issues/12#issuecomment-380344479 for details.
