### ISSUE TITLE
Traces are being recorded for ignored patterns

### ISSUE THREAD

**Issue by d1mnewz** [opentracing-contrib/csharp-netcore#36]
There is an option to ignore some tracing patterns as described here - #28 
Steps to reproduce: 
0. Setup: ASP.NET Core 2.2, OpenTracing.Contrib.NetCore 0.5.0
1. Have the following code.
MonitoringController.cs 
```
        [HttpGet]
        [Route("health")]
        public IActionResult Health()
        {
            var state = StateManager.CurrentState;
            if (state is State.RequiresRestart)
            {
                this.log.Warning("Health probe was requested, but service is in {State} state", state);
                return this.StatusCode(503);
            }

            return this.Ok();
        }
```
Startup.cs
```
            services.AddJaeger().AddOpenTracing(builder =>
                builder.ConfigureAspNetCore(options =>
                {
                    // ignore certain requests to prevent spamming the tracer with irrelevant data
                    options.Hosting.IgnorePatterns.Add(request =>
                        request.Request.Path.Value?.StartsWith("/monitoring") == true);
                }));
```
2. Call **GET** `/monitoring/health` endpoint.

Expected behaviour: No traces were reported for this call. 
Actual behaviour: Traces were recorded for this call.
![image](https://user-images.githubusercontent.com/11834902/50773061-60362180-1298-11e9-8165-db7cfcce97fb.png)

So, I went on and fixed it with PR #35 where you can see the reason of this bug.

**Comment by tillig** [comment]
I figured out some middleware that sets the `SamplingPriority` tag on a span based on the inbound `X-B3-Sampled` header, if present. I put it in [the issue on the Jaeger repo](https://github.com/jaegertracing/jaeger-client-csharp/issues/121#issuecomment-460359501)

I'm trying to figure out if it's something that should happen in `HostingEventProcessor` or if it should be middleware provided here... or if it's just something that I keep in my own repo. I'd be happy to PR it to the right place.

**Comment by d1mnewz** [comment]
Should we close the issue?
My PR fixed that for us, @tillig what about you?

**Comment by tillig** [comment]
As noted in [my earlier comment](https://github.com/opentracing-contrib/csharp-netcore/issues/36#issuecomment-459531709)

> PR #35 looks like it'll handle the hosting and MVC parts but not the EF bit.

Basically, this fixes one of the issues, but it doesn't actually enforce it at all levels. So, no, unfortunately the PR didn't totally resolve this for me.

**Comment by cwe1ss** [comment]
The new v0.7.0 release now supports this via the `options.StartRootSpans` property on all `Configure*()` methods. If ASP.NET Core instrumentation is enabled (which happens automatically when it is an ASP.NET Core application), all other instrumentation is set to `StartRootSpans = false`. This means that no spans are created if the ASP.NET Core request is ignored via the `IgnorePatterns` option.

The library still creates spans if running in a regular console application. In that case, you have to configure the library to your liking.
