### ISSUE TITLE
Add NuGet package information (logo, description)

### ISSUE THREAD

**Issue by cwe1ss** [opentracing-contrib/csharp-netcore#4]
Questions:
* Can we use the OpenTracing logo?

**Comment by cwe1ss** [comment]
I added the package description and tags. I'll clarify the usage of the logo later.

**Comment by cwe1ss** [comment]
@bhs @tedsuo @yurishkuro Can I use the OpenTracing logo for contrib projects on nuget.org (the .NET package manager)?

The [official `OpenTracing` package](https://www.nuget.org/packages/OpenTracing/) currently uses [this logo](https://avatars0.githubusercontent.com/u/15482765). I'd like to use the same for [`OpenTracing.Contrib.NetCore`](https://www.nuget.org/packages/OpenTracing.Contrib.NetCore/).

**Comment by bhs** [comment]
> Can I use the OpenTracing logo for contrib projects

Of course!

**Comment by yurishkuro** [comment]
Officially the logo is the trademark of The Linux Foundation. Here's there policy: https://www.linuxfoundation.org/trademark-usage/

In particular, this paragraph would seem to imply that you can freely link to OT site via logo

> You are also allowed to use a trademark or logo of The Linux Foundation as a link to the home page of the applicable project or to a web page on The Linux Foundation web site that is relevant to the reference so long as the link is in a manner that is consistent with the preservation of the goodwill and value of the mark.  The link and all other usage of a logo of The Linux Foundation shall be done using the official versions of The Linux Foundation logos obtained from The Linux Foundation or its projects.

**Comment by cwe1ss** [comment]
Thank you for your responses. The logo will be used in the next version.
