### ISSUE TITLE
No custom logs when using Serilog

### ISSUE THREAD

**Issue by Marusyk** [opentracing-contrib/csharp-netcore#42]
## Requirement - what kind of business use case are you trying to solve?

I need to send to Jaeger custom logs. Now it works only when I use `Microsoft.Extensions.Logging.ILoggerFactory`

My Startup
```csharp
public void ConfigureServices(IServiceCollection services)
{
	services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

	services.AddOpenTracing();
	services.AddSingleton<ITracer>(sp =>
	{
		var loggerFactory = sp.GetRequiredService<ILoggerFactory>();

		var reporter = new RemoteReporter.Builder()
			.WithSender(new UdpSender())
			.WithLoggerFactory(loggerFactory)
			.Build();		

		var tracer = new Tracer
				.Builder("Sample service")
			.WithReporter(reporter)
			.WithSampler(new ConstSampler(true))
			.Build();

		GlobalTracer.Register(tracer);
		return tracer;
	});
}
```
Somewhere in controller:
using Microsoft.Extensions.Logging;

```csharp
namespace WebApplication2.Controllers
{
    [Route("api/[controller]")]
    public class ValuesController : ControllerBase
    {
        private readonly ILogger<ValuesController> _logger;

        public ValuesController(ILogger<ValuesController> logger)
        {
            _logger = logger;
        }
		
        // GET api/values/5
        [HttpGet("{id}")]
        public ActionResult<string> Get(int id)
        {
            _logger.LogWarning("Get values by id: {valueId}", id);
            return "value";
        }
```
Result
![image](https://user-images.githubusercontent.com/9221694/57532263-f7dd7680-7343-11e9-90ec-cef1829fa13a.png)

## Problem - what in Jaeger blocks you from solving the requirement?

But when I use Serilog, there are no any custom logs. I just install serilog and add

```csharp
public static IWebHostBuilder CreateWebHostBuilder(string[] args)
{
	return WebHost.CreateDefaultBuilder(args)
		.UseStartup<Startup>()
		.UseSerilog();
}
```
Could you please suggest why custom logging doesn't work with Serilog?

**Comment by nblumhardt** [comment]
This is a limitation in the Serilog logger factory implementation; in particular, Serilog currently ignores added providers and assumes that Serilog Sinks will replace them instead. Some work is underway to alleviate this with: https://github.com/serilog/serilog-extensions-logging/pull/132 - any and all input/assistance appreciated.

(Another, probably quicker short-term option might be to implement a simple `WriteTo.OpenTracing()` method to connect Serilog directly to OpenTracing without using MEL as the intermediary - happy to help out if someone is exploring that approach.)

**Comment by Marusyk** [comment]
@nblumhardt Thank you very much for response. It would be great to have some solution for now. Could you please suggest how to implement `WriteTo.OpenTracing()` or share any tutorials/articles? 
Thank you in advance.

**Comment by nblumhardt** [comment]
Hi @Marusyk 

`WriteTo.OpenTracing()` would just be a convenience wrapper for `WriteTo.Sink(new OpenTracingSink(...))`, so the sink class would be the best place to start.

This would need to implement Serilog's `ILogEventSink`, and do almost exactly what [this method](https://github.com/opentracing-contrib/csharp-netcore/blob/master/src/OpenTracing.Contrib.NetCore/Logging/OpenTracingLogger.cs#L33) does - accept a `LogEvent` from Serilog, convert its properties into a fields dictionary, and pass these through `_tracer.ActiveSpan.Log(...)`.

There are quite a lot of implementations of `ILogEventSink` out there to examine for examples (any _Serilog.Sink.*_ will have one.

The trick will be how to get an `ITracer` into the sink, somehow - either via its constructor or some other mechanism. Order of initialization can be a bit tricky but generally there's a way :-)

Hope this helps!
Nick

**Comment by Marusyk** [comment]
Thanks a lot. It was very helpful. My implementations of that:
```csharp
public class OpenTracingSink : ILogEventSink
{
	private readonly ITracer _tracer;
	private readonly IFormatProvider _formatProvider;

	public OpenTracingSink(ITracer tracer, IFormatProvider formatProvider)
	{
		_tracer = tracer;
		_formatProvider = formatProvider;
	}

	public void Emit(LogEvent logEvent)
	{
		ISpan span = _tracer.ActiveSpan;

		if (span == null)
		{
			// Creating a new span for a log message seems brutal so we ignore messages if we can't attach it to an active span.
			return;
		}

		var fields = new Dictionary<string, object>
		{
			{ "component", logEvent.Properties["SourceContext"] },
			{ "level", logEvent.Level.ToString() }
		};

		fields[LogFields.Event] = "log";

		try
		{
			fields[LogFields.Message] = logEvent.RenderMessage(_formatProvider);
			fields["message.template"] = logEvent.MessageTemplate.Text;

			if (logEvent.Exception != null)
			{
				fields[LogFields.ErrorKind] = logEvent.Exception.GetType().FullName;
				fields[LogFields.ErrorObject] = logEvent.Exception;
			}

			if (logEvent.Properties != null)
			{
				foreach (var property in logEvent.Properties)
				{
					fields[property.Key] = property.Value;
				}
			}
		}
		catch (Exception logException)
		{
			fields["mbv.common.logging.error"] = logException.ToString();
		}

		span.Log(fields);
	}
}

public static class OpenTracingSinkExtensions
{
	public static LoggerConfiguration OpenTracing(
			  this LoggerSinkConfiguration loggerConfiguration,
			  IFormatProvider formatProvider = null)
	{
		return loggerConfiguration.Sink(new OpenTracingSink(GlobalTracer.Instance, formatProvider));
	}
}
```

**Comment by nblumhardt** [comment]
Fantastic, thanks for the update @Marusyk 

After we have the new functionality merged, there will need to be some downstream changes before this will be picked up, but ideally - yes, the goal is to not require this.
