### ISSUE TITLE
Release v0.6.0

### ISSUE THREAD

**Issue by austinlparker** [opentracing-contrib/csharp-netcore#43]
@cwe1ss would you be able to release in AppVeyor?

**Comment by cwe1ss** [comment]
v0.6.0 is now available on NuGet: https://www.nuget.org/packages/OpenTracing.Contrib.NetCore/0.6.0

PS: I'd like to apologize for ghosting this repo. I've been involved in a very stressful project over the last 6 months and had to ignore all OSS stuff to stay healthy. 

PS 2: I'm personally no longer using this library in a project so my involvement will probably stay low. I also don't yet know what the current OpenTracing + OpenCensus = OpenTelemetry merger means for this project. Didn't have time yet to read about all of this.

**Comment by austinlparker** [comment]
Thanks! Don't worry about having to step away, we're all one big team. :)

As far as the OpenTelemetry stuff goes, I wouldn't worry about it too much for right now. There's a planned bridge from OpenTracing -> OpenTelemetry, so any current users of this library should be fine.  In addition, I would expect a similar library to be available for OpenTelemetry .NET as it gets closer to release, possibly forked from this one or incorporating parts of its design. You can check out https://github.com/open-telemetry/opentelemetry-dotnet for more info or to keep tabs on the progress, we'd love to have you involved if your schedule clears up!

**Comment by austinlparker** [comment]
That said, it might be beneficial if you add me to the AppVeyor project in case we need to do further releases of this? austinlparker@gmail.com is my email on there.

**Comment by lghinet** [comment]
there is a big issue in this version #44

**Comment by cwe1ss** [comment]
I'm in contact with @austinlparker via email regarding admin permissions for AppVeyor so I'm closing this issue.
