### ISSUE TITLE
Span has already been finished 

### ISSUE THREAD

**Issue by lghinet** [opentracing-contrib/csharp-netcore#44]
using the new version 0.6.0, ef starts a span and then sqlClient starts an inner span which is wrong, resulting in .. 

"Span has already been finished; will not be reported again. Operation: "sqlClient MERGE" Trace Id: "54d95a5926fc16ce" Span Id: "41c65e24e9365bcd""

**Comment by austinlparker** [comment]
Can you provide a code sample that reproduces this issue?

**Comment by lghinet** [comment]
[ConsoleApp1.zip](https://github.com/opentracing-contrib/csharp-netcore/files/3245951/ConsoleApp1.zip)

**Comment by lghinet** [comment]
you can see that it enters in both 
EntityFrameworkCoreDiagnostics and SqlClientDiagnostics starting two inner spans

**Comment by agilob** [comment]
I'm getting a lot of these when project is deployed in docker and accessed via traefik with jaeger tracing enabled.

```
20:08:21.270 [default] [XNIO-1 task-18] WARN  io.jaegertracing.internal.JaegerSpan - Span has already been finished; will not be reported again.
20:08:31.265 [default] [XNIO-1 task-19] WARN  io.jaegertracing.internal.JaegerSpan - Span has already been finished; will not be reported again.
20:08:41.267 [default] [XNIO-1 task-20] WARN  io.jaegertracing.internal.JaegerSpan - Span has already been finished; will not be reported again.
20:08:51.262 [default] [XNIO-1 task-21] WARN  io.jaegertracing.internal.JaegerSpan - Span has already been finished; will not be reported again.
20:09:01.256 [default] [XNIO-1 task-22] WARN  io.jaegertracing.internal.JaegerSpan - Span has already been finished; will not be reported again.
20:09:11.255 [default] [XNIO-1 task-23] WARN  io.jaegertracing.internal.JaegerSpan - Span has already been finished; will not be reported again.
20:09:21.268 [default] [XNIO-1 task-24] WARN  io.jaegertracing.internal.JaegerSpan - Span has already been finished; will not be reported again.
20:09:31.255 [default] [XNIO-1 task-25] WARN  io.jaegertracing.internal.JaegerSpan - Span has already been finished; will not be reported again.
```

**Comment by phxnsharp** [comment]
I am getting this as well. For us it appears to be related to a "Follows From" type relationship which happens well after the original span has completed.

**Comment by cwe1ss** [comment]
v0.7.0 now uses a different mechanism to correlate spans for EF Core & SqlClient. This will hopefully eliminate this issue. It no longer appeared on the samples projects.
