### ISSUE TITLE
Point to OpenTelemetry

### ISSUE THREAD

**Issue by enzian** [opentracing-contrib/csharp-netcore#45]
As far as I can tell, work on this project has generally stopped an the future of the opentracing standard is not opentelemetry!

Can we make this clean in the description of this repo and point to https://github.com/open-telemetry/opentelemetry-dotnet?

**Comment by cwe1ss** [comment]
I'm not using this project myself right now but there seem to be some other people using it.  

I've not looked into the details of OpenTelemetry yet but as far as I've seen there will be support for ASP.NET Core ( https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Collector.AspNetCore ) and for HttpClient requests (https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Collector.Dependencies ).

In my opinion, this project is obsolete once the OpenTelemetry client is available. Does anyone know when that will happen?

Given that, I'd be ok with investing a few more hours here if anyone needs a critical thing until OpenTelemtry is released, but I don't think it makes sense for anyone to invest much more time here. Instead, we should probably all focus on OpenTelemetry and contribute there.

What do other people think about this?

**Comment by austinlparker** [comment]
There's an alpha version of OpenTelemetry for .NET that's currently available, and we're expecting a beta by the end of September. I'd encourage anyone that's using this project to start looking at the OpenTelemetry SDK and file issues/make PR's to improve the instrumentation for ASP.NET Core/HttpClient over there.

**Comment by pcwiese** [comment]
If this project is unsupported for ASP.NET Core 3.0 we should specifically say so. I'm currently writing/testing the OpenTelemetry C# shim between OpenTracing and OpenTelemetry and I'm running into problems with OpenTracing around camel cased PropertyFetcher properties as mentioned in a different issue. Obviously I can't test the shim on 3.0 if this project is non-functional.

**Comment by austinlparker** [comment]
I'm personally fine calling this unsupported for Core 3.0... I am curious if people who are trying to use this with Core 3 (like in #48) would be OK migrating to OpenTelemetry now/soon?

**Comment by pcwiese** [comment]
I think we should make OpenTracing work with ASP.NET Core 3.0.

Given that OpenTelemetry is not ready yet and the latest version of this library doesn't function with ASP.Net netcore 3.0 people are left with no usable distributed tracing libraries on 3.0. It leaves people in limbo.

The OpenTelemetry public API is missing key features like recording spans for out of band events. My team utilizes out of band EventSource events for nearly everything so we are going to wait for a the OpenTelemetry RFC (https://github.com/open-telemetry/rfcs/commit/32b078c8e1ba695be47c1b8874dc96b0921e79f2) to be implemented before even attempting to incorporate OpenTelemetry. That leaves us with OpenTracing in the short to medium term.

**Comment by cwe1ss** [comment]
I added some text and a link to OpenTelemetry-dotnet to the readme.
