### ISSUE TITLE
Different "TraceID" and other meta data between opentracing-contrib and "Diagnostics" of Asp.Net Core

### ISSUE THREAD

**Issue by tungphuong** [opentracing-contrib/csharp-netcore#46]
I am using .net core 3.0 preview 7, open tracing and Jaeger. Everything is working well, however, there is one thing is unclear that is the value of tracer Id of "GlobalTracer.Tracer" and "Diagnostics" are different.

```
[14:59:19 INF {"SourceContext": "Service1", "RequestId": "0HLOR1KJB6A9N:00000001", "RequestPath": "/Ping", "SpanId": "440b50a4411904c8", "TraceId": "6bf28db9-46118e6c32a3875b", "ParentId": "", "Environment": "Development", "ApplicationName": "Lead-Service", "TraceId_OpenTracing": "440b50a4411904c8"}] 123456
``` 

Please look at the value of "TracerId" and "TraceId_OpenTracing"

So, how can we configure to values are the same? 

```
Workaround

public class OpenTracingContextLogEventEnricher : ILogEventEnricher
    {
        public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
        {
            var tracer = GlobalTracer.Instance;
            if (tracer?.ActiveSpan == null)
            {
                return;
            }
            logEvent.AddOrUpdateProperty(propertyFactory.CreateProperty("TraceId", tracer.ActiveSpan.Context.TraceId));
            logEvent.AddOrUpdateProperty(propertyFactory.CreateProperty("SpanId", tracer.ActiveSpan.Context.SpanId));
        }
    }
```

**Comment by alexeyzimarev** [comment]
OpenTracing interfaces don't allow supplying external ids for span id and trace id. As far as I can see, this library doesn't use anything from the Activity except tags. I am working on the same issue now. If System.Diagnostic is configured to use W3C id format, it will generate perfectly usable ids but there's no way to propagate those ids to `SpanContext`, except using reflections, like in the mentioned workaround...

**Comment by cwe1ss** [comment]
This library does not handle trace IDs in any way. It's up to the OpenTracing tracer (Jaeger, ...) to handle/set them, so you'd have to ask there if anything should be changed. 

fyi: For System.Diagnostic.Activity's, you can set the desired format via `System.Diagnostics.Activity.DefaultIdFormat`. I "think" the default changed to W3C in .NET 5.
