### ISSUE TITLE
Using Polly Retry causes error: An item with the same key has already been added. Key: ot-Span

### ISSUE THREAD

**Issue by mustakimali** [opentracing-contrib/csharp-netcore#51]
Looking at the code

https://github.com/opentracing-contrib/csharp-netcore/blob/master/src/OpenTracing.Contrib.NetCore/CoreFx/HttpHandlerDiagnostics.cs#L74-L75

```
// This throws if there's already an item with the same key. We do this for now to get notified of potential bugs.
request.Properties.Add(PropertiesKey, span);
```

Yes this throws an error when Polly is configured to retry a failed Http request.

**Comment by austinlparker** [comment]
Fix for this was released in v0.6.2
