### ISSUE TITLE
Can´t trace exceptions

### ISSUE THREAD

**Issue by tcfialho** [opentracing-contrib/csharp-netcore#55]
With the latest version, i cant trace exceptions... My test case is just an endpoint that throws an exception. Log section not show any exception in Logs stack. 

I am using net core 3.1, jaeger 0.3.6 and OpenTracing.Contrib.NetCore 0.6.2.

**Comment by cwe1ss** [comment]
Is this still relevant? Do you have an error handler that catches the exception? I've just tested it with `UseDeveloperExceptionPage` and without any exception handler (which forces the UnhandledException logic) and both logged the error.

**Comment by cwe1ss** [comment]
I'm closing this as there hasn't been any further feedback. please comment or create a new issue if this problem still exists in the latest version.
