### ISSUE TITLE
Can't  control which Sql Command will create a span

### ISSUE THREAD

**Issue by barispeker** [opentracing-contrib/csharp-netcore#65]
Need:
In our system micro-services share internally developed framework which executes SqlCommands for each transactions in background. For a given trace where are a lot of spans which developer may not be concerned, so we need someway to determine which SqlCommand will create a span.

Proposal:
SqlClientDiagnosticOptions can include OperationNameResolver like delegate to give control whether a span will be created for given SqlCommand or not.

Ps: i will create a PR for this need. thanks.

**Comment by cwe1ss** [comment]
With the next release it will be possible to ignore SQL commands by doing the following:

```csharp
services.AddOpenTracing(builder =>
{
    builder.ConfigureSqlClientDiagnostics(options =>
    {
        // Ignore all SELECT statements
        options.IgnorePatterns.Add(cmd => cmd.CommandText.StartsWith("SELECT "));
    });
});
```

If you're working with Entity Framework Core, you need a different call since EF Core no longer uses SqlClient under the hoods:

```csharp
services.AddOpenTracing(builder =>
{
    builder.ConfigureEntityFrameworkCore(options =>
    {
        options.IgnorePatterns.Add(cmd => cmd.Command.CommandText.StartsWith("SELECT"));
    });
});

```
