### ISSUE TITLE
this project can't open by visual studio 2019?

### ISSUE THREAD

**Issue by qozm** [opentracing-contrib/csharp-netcore#71]
when open "OpenTracing.Contrib.sln" by visual studio 2019, all projects show "unloaded"?

![1](https://user-images.githubusercontent.com/7522721/92262658-1048ab80-ef0e-11ea-9dbb-b7a8ac5df01e.PNG)

**Comment by cwe1ss** [comment]
This happens because the project contains a global.json that pins the .NET Core SDK version to `2.1.401`. Until the project is updated, you'd have to either install this exact SDK version or use a newer version and resolve any build errors.

**Comment by cwe1ss** [comment]
The solution now requires the latest 3.1 SDK (3.1.402), so I'm closing this issue.
