### ISSUE TITLE
Project seems to be targeting netcoreapp2.1 and 3.1, but nuget package depends on netcoreapp2.0

### ISSUE THREAD

**Issue by MarkusGeigerITD** [opentracing-contrib/csharp-netcore#78]
Hi!
From looking at the sources and examples, this library seems to be targeting netcoreapp2.1 and 3.1 but there's no nuget package with these targets available,
Since netcore 2.0 is out of support for a while and netcore 2.1 will go out of support next summer, will there be a nuget package dual-targeting 2.1 and 3.1 soon?

Thanks for your work!
Markus

**Comment by hmehr** [comment]
Also to add to this question, is there any plan to support .net 5?

**Comment by MarkusGeigerITD** [comment]
Seems like someone else got impatient, too and published a 2.1/3.1 under the 0.63 version tag and a 5.0 unter as 0.65

https://www.nuget.org/packages/Mcclane007.OpenTracing.Contrib.NetCore/

I think that is a very unfortunate situation since it leads to fragmentation and it could easily be resolved by just releasing the current state as a new package.

**Comment by cwe1ss** [comment]
v0.7.0 now targets .NET Core 2.1, .NET Core 3.1 & .NET 5.0.

**Comment by MarkusGeigerITD** [comment]
Great! Thanks, Christian!
